### ISSUE TITLE
Safari: "Enter" key in control label opens repeat menu

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4495] opened 2020-04-11 00:04 UTC
Steps in Form Builder:

- repeated grid
- control in other grid
- enter label, use "Enter" key
- menu shows

Doesn't happen with Chrome or Firefox.

Here I did "Enter" in the "Number" label.

<img width="520" alt="Screen Shot 2020-04-10 at 5 02 24 PM" src="https://user-images.githubusercontent.com/105769/79030290-231ca700-7b4d-11ea-8962-898b2497e4d2.png">

**Comment by avernet** [comment] 2020-08-05 05:58
I can't reproduce this now, and suspect this has been fixed by 0121e89bc2634a6ada56fe045a1717001911d0e6.

**Closed by avernet** 2020-08-05 05:58 UTC
Labels: Module: Form Builder
