### ISSUE TITLE
Support lhha pointing to control inside a repeat

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#241] opened 2012-05-17 17:20 UTC
- Ideally, the `for` on the label would be:
  - Empty if the there are no iterations (repeat pointing to an empty sequence).
  - Otherwise pointing to the effective id of the control in the current iteration.
- If the above can't be done quickly enough, always pointing to the control in the "first iteration" would still be a significant improvements over the current situation.

[Test case](http://localhost:8080/orbeon/xforms-sandbox/run?url=https://raw.github.com/gist/2720323/label-outside-repeat.xhtml)

**Comment by ebruchez** [comment] 2016-06-20 23:38
This would still be nice to have as it would help remove `fr:grid` hacks as discussed in #2783.

If we do this, in addition to what is discussed above, we must consider what to do for `required`. Two ways:

- Statically. If we can know which `bind/@required` we are associated with, then we can know statically whether controls will be required, and put an `xforms-required` class on the label. Alternatively, Form Builder could place an `xforms-required` class on the associated `<xf:label>` element when this is the case.
- Dynamically. If requiredness is not static, and at least in the case where there is at least one relevant repeated control, we can obtain all `required` values and, if all `true()`, add the `xforms-required` class at runtime dynamically.

**Comment by ebruchez** [comment] 2017-10-17 16:58
See also  #3337 about using `aria-labelledby`.

**Comment by ebruchez** [comment] 2017-10-17 23:29
Implementation:

- [x] non-local all LHHA have a dynamic representation, `XFormsLHHAControl`
  - this also helps simplify `MutableLHHAProperty`
- [x] `MutableLHHAProperty` asks `XFormsLHHAControl` for its value
- [ ] handle client-side updates to external LHHA outside of repeats
- [ ] output `labelledby` attribute
- [ ] check whether that attribute ever needs to change value (nested repeats?)
- [ ] for the label, controls should still output a `<label>` element but hidden

**Comment by ebruchez** [comment] 2017-10-19 23:35
For the "required" marking, in case there is no iteration, we don't really care to show the star, IMO. So I think that showing it if one or all controls that are required is fine. Proposed solution:

- use a `class` on the external `<xf:label for="...">`
- `grid.xbl` places that class based on resolving the node for the first control, which can be expressed with `*[1]/*[local-name() = $control-name]`, or we could update the `bind()` function to resolve like variables

**Comment by ebruchez** [comment] 2017-10-20 04:21
[Documented](https://doc.orbeon.com/xforms/controls/lhh.html)

**Comment by ebruchez** [comment] 2017-11-29 18:30
For XBL support, we need `StaticLHHASupport.llh()` to contain already the label referred to by `xxbl:label-for`. This can be computed statically.

**Comment by avernet** [comment] 2017-12-11 23:51
This looks like an issue with @ebruchez: in a repeated grid with a required input, if we have one row in the grid, the `xforms-label` in the grid header has the `xforms-required` class, as expected. However, add a row, and it looses the `xforms-required` class.

**Comment by ebruchez** [comment] 2017-12-15 00:17
`xforms-required` issue caused by #3394.

**Comment by ebruchez** [comment] 2017-12-15 00:22
It seems that we covered everything, so closing now.

**Closed by ebruchez** 2017-12-15 00:22 UTC
Labels: Accessibility, XForms
