### ISSUE TITLE
Language selector appearance reverts to dropdown

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3327] opened 2017-08-22 18:31 UTC
Customers have reported, and we have occasionally observed, that at times the language selector reverts to showing as a drop-down. When this happens, restarting the server typically solves the problem.

Form Runner produces an `<xf:select1 appearance="bootstrap">`, which is implemented in `bootstrap-select1.xbl`. What we observe is as if Orbeon Forms in some cases wasn't able to find that XBL component, and was thus rendering the component as a plain drop-down.

Unfortunately, we are at this time unable to reliably reproduce this issue.

![Language selector is shown as drop-down](https://user-images.githubusercontent.com/106961/29580860-4f5e57a4-872c-11e7-9cd0-0e2db42c85b1.png)

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016743/messages/423044100)

**Comment by avernet** [comment] 2017-08-22 21:02
The XBL index is kept in `BindingMetadata._xblIndex` and we have code in `BindingIndex.findMostSpecificBinding` to look for the specific binding within the index. It's possible that, under some circumstances, that code doesn't find the binding we're interested in because the code:

- first finds another binding, which isn't the one we're looking for, or
- doesn't find the binding because it isn't in the index at that time, or
- doesn't find the binding because it looks incorrectly.

When able to reproduce the issue, we could add debugging code in `findMostSpecificBinding` logging the content of the index.

**Comment by ebruchez** [comment] 2017-08-23 16:31
Possible [+1 from customer](https://3.basecamp.com/3600924/buckets/1979712/messages/301082851#__recording_647348750) for `fr:character-counter`.

**Comment by ebruchez** [comment] 2017-08-28 16:31
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/653711424)

**Comment by ebruchez** [comment] 2017-09-20 18:51
Happened to me just now in Form Builder while developing.

See https://gist.github.com/ebruchez/4e978f956ebd5132e356d88c845f637e where I logged the index as `index1.scala` and after a subsequent restart the index as `index2.scala`. Clearly some bindings are missing in `index1.scala` but we knew that already.

**Comment by ebruchez** [comment] 2017-10-18 04:22
Possible way to reproduce:

- put `grid.xbl` in `resources-local/` folder
- make it cause an error (for example duplicate id)
- load Form Builder
- notice error
- move `grid.xbl` to `grid.xbl.bak`
- reload Form Builder
- check language selector

I still need to confirm these steps.

**Comment by ebruchez** [comment] 2017-12-20 17:26
Possible [+1 from user](https://stackoverflow.com/questions/47840199/why-are-the-html-ids-generated-by-orbeon-and-the-proxy-portlet-sometimes-inconsi/47874138)

**Comment by avernet** [comment] 2018-03-12 23:21
I am not sure if the exact type of error matters, but using a duplicate id I wasn't able to reproduce the issue. That is, after moving `grid.xbl` to `grid.xbl.bak` and reloading the Form Builder the language selector still shows normally.

**Comment by ebruchez** [comment] 2018-05-02 17:54
Success reproducing this way:

- stop Tomcat
- in `view.xsl`, before `fr-language-selector`, add (note the duplicate id):
    ```xml
    <xf:group id="xxx1"/>
    <xf:group id="xxx1"/>
    ```
- start Tomcat
- load Form Builder, error shows
- in `view.xsl`, comment out the second group:
    ```xml
    <xf:group id="xxx1"/>
    <!--<xf:group id="xxx1"/>-->
    ```
- load Form Builder, language selector is a plain dropdown

**Comment by ebruchez** [comment] 2018-05-02 18:12
Findings:

- when error happens, `updateIndex()` is not called, as should be the case
- when error is fixed, `updateIndex()` is called, but the index doesn't contain `fr:bootstrap-select1`

**Comment by ebruchez** [comment] 2018-05-02 18:31
In `getUpToDateLibraryAndBaseline`:

- even though the index is not updated upon error, `oxf.xforms.xbl.library` and `oxf.xforms.resources.baseline` properties get associated with path information
- the next time `getUpToDateLibraryAndBaseline` runs, because  properties haven't changed, `reloadLibraryAndBaseline` doesn't run and so controls in the library/baseline do not make it to the index

**Comment by ebruchez** [comment] 2018-05-02 22:27
[+1 from customer](https://3.basecamp.com/3600924/buckets/5987825/messages/1050881832)

**Comment by ebruchez** [comment] 2018-05-02 22:36
We now have a fix for the case we reproduced. We don't know if the issue can happen in other scenarios.

**Comment by ebruchez** [comment] 2018-05-02 22:37
- [] once the fix is confirm to work for at least one customer, notify other customers/users

**Comment by ebruchez** [comment] 2018-06-25 21:58
Notified customers/users. We still don't know if it can still happen with that patch, but closing for now.

**Closed by ebruchez** 2018-06-25 21:58 UTC
Labels: Form Runner, Top issue

**Comment by ebruchez** [comment] 2019-02-14 18:39
Confirming that, on a customer branch where I can reproduce the problem (by using a non-existing XPath function, loading the form, fixing the problem, and loading again), that cherry-picking this fix works in this case too.
