### ISSUE TITLE
Support minimizing the "above the baseline" JavaScript files

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#841] opened 2013-02-20 02:15 UTC
Right now we only minify the "below the baseline" JavaScript files, and link to the JavaScript files and their corresponding minified version is "hardcoded" in [`XFormsFeatures.java`](https://github.com/orbeon/orbeon-forms/blob/master/src/java/org/orbeon/oxf/xforms/processor/XFormsFeatures.java).

**Comment by ebruchez** [comment] 2016-11-30 20:17
Marking as duplicate of #2328.

**Closed by ebruchez** 2016-11-30 20:17 UTC
Labels: Performance, RFE, XForms
