### ISSUE TITLE
Lease info shows badly formatted numbers after expiration

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3930] opened 2019-02-04 22:46 UTC
Right after expiration, when dialog shows:

<img width="963" alt="screen shot 2019-02-04 at 2 43 11 pm" src="https://user-images.githubusercontent.com/105769/52242448-92cd3d00-288b-11e9-81fc-deeeae0bc8da.png">

After saying "No" in lease renewal dialog:

<img width="972" alt="screen shot 2019-02-04 at 2 43 28 pm" src="https://user-images.githubusercontent.com/105769/52242447-92cd3d00-288b-11e9-8836-1068be83b1b9.png">

**Comment by avernet** [comment] 2019-06-18 18:48
Closing for now, as I can't reproduce this. We'll reopen it if we see it again during testing, since this is part of the test plan.

**Closed by avernet** 2019-06-18 18:48 UTC
Labels: Module: Form Runner, Priority: Regression
