### ISSUE TITLE
Reusable HTTP Services and Actions across forms

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3755] opened 2018-09-20 21:04 UTC
In a way similar to section templates, users often would like to have HTTP Services and/or Actions "templates", that are defined somewhere and can be pulled into a form to be reused.

It would be nice of the reusable HTTP Services and Actions where not just seen as something that gets copied into the form and the form authors are expected to modify, but more like reusable blocks that can be "bound" to certain inputs and/or outputs (XPath or field for input, field or dataset for output).

[+1 from customer](http://discuss.orbeon.com/Section-template-with-an-HTTP-service-and-an-action-td4662799.html)

**Comment by ebruchez** [comment] 2021-08-04 18:09
Duplicate of #1474, closing.

**Closed by ebruchez** 2021-08-04 18:09 UTC
Labels: Module: Form Builder, Type: RFE
