### ISSUE TITLE
Show in Summary/Search has no effect on control in section templates

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2616] opened 2016-03-16 17:55 UTC
To reproduce, use the following library/form:
- [library.txt](https://github.com/orbeon/orbeon-forms/files/176576/library.txt)
- [form.txt](https://github.com/orbeon/orbeon-forms/files/176577/form.txt)

**Comment by ebruchez** [comment] 2017-05-05 01:42
Duplicate of #3173, which just got fixed.

**Closed by ebruchez** 2017-05-05 01:42 UTC
Labels: Form Runner
