### ISSUE TITLE
Cannot read property 'firstChild' of null on Form Builder summary page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3094] opened 2017-01-31 18:31 UTC
Just loading the Form Builder summary page is enough to reproduce the problem.

![screen shot 2017-01-31 at 10 30 57 am](https://cloud.githubusercontent.com/assets/106961/22478831/6ccf3c4e-e7a0-11e6-9f07-60628442bea4.png)
![screen shot 2017-01-31 at 10 31 13 am](https://cloud.githubusercontent.com/assets/106961/22478832/6cd6f2ea-e7a0-11e6-9fc8-887010554a5c.png)

**Comment by ebruchez** [comment] 2017-01-31 18:36
Duplicate of #3090.

**Comment by ebruchez** [comment] 2017-01-31 18:36
So closing.

**Closed by ebruchez** 2017-01-31 18:36 UTC
Labels: Form Builder, Regression
