### ISSUE TITLE
Ability to add/create "a number" of repeat iteration

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3104] opened 2017-02-03 17:24 UTC
For instance, imagine a form with a field "number of children". Upon value change on that field, the form would make sure that a given repeated grid or repeated section has at the number of iteration specified in the field "number of children". That repeated grid or repeated section wouldn't provide a way for users to add/remove iterations, as the number of iterations would be driven by the value of the "number of children" field.

**Comment by ebruchez** [comment] 2017-02-14 21:56
Should not be hard to do now that the Actions Editor response tab is more flexible.

**Comment by ebruchez** [comment] 2017-06-07 21:14
Duplicate of #1658.

**Closed by ebruchez** 2017-06-07 21:14 UTC
Labels: Form Builder, Form Runner, RFE
