### ISSUE TITLE
new rows in master-grid are not synchronized with detail-section

### ISSUE THREAD

**Issue by patricsteiner** [orbeon/orbeon-forms#3981] opened 2019-03-12 21:26 UTC
Recently, the new Master-Detail Feature was introduced: https://doc.orbeon.com/form-builder/advanced/services-and-actions/synchronize-repeated-content

It seems that this functionality is now partly broken. 

**Expected behaviour**
When I add a new row in a master-grid of a properly configured Master-Detail view, a new row is also added to the corresponding detail-section.

**Observed behaviour**
Row is not added. However, when a row is edited or deleted, it is properly synchronized.

**Steps to reproduce**
Open this form in the test modus and add a new row to the master-grid. No row is added to the detail-grid.
https://demo.orbeon.com/demo/fr/orbeon/builder/edit/ff7daa2dc7aec866297e0a79d967ade837d8b57d

**Comment by ebruchez** [comment] 2019-03-12 23:04
@patricsteiner Are you using Orbeon Forms 2018.2.2? Issue #3956 looks like what you are describing and is fixed in that version.

**Comment by ebruchez** [comment] 2019-03-12 23:05
Also, it looks that we haven't yet updated demo.orbeon.com, which still runs on Orbeon Forms 2018.2.1.

**Comment by patricsteiner** [comment] 2019-03-12 23:18
Oh I didn't find that issue - sorry. Good to know it's already fixed, thanks :)

**Comment by ebruchez** [comment] 2019-03-14 23:17
No problem. In that case I am closing this as duplicate of #3956.

**Closed by ebruchez** 2019-03-14 23:17 UTC
