### ISSUE TITLE
Ability to delete published forms

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4154] opened 2019-08-11 05:19 UTC
Right now Orbeon Forms only supports making forms as unavailable, while in some cases admins might want to completely remove published forms. This could for instance be the case if the forms have been published by mistake, or, more generally, when admins know the forms won't be needed anymore and there is no need to keep them around.

This should be straightforward if we have no data for the forms to delete. If data exists, we might want to warn admins, and maybe offer the option to also delete the corresponding data.

[+1 from user](https://stackoverflow.com/questions/57437460)

**Comment by ebruchez** [comment] 2019-08-12 04:34
Closing as duplicate of #3597. Comment copied over.

**Closed by ebruchez** 2019-08-12 04:34 UTC
Labels: Module: Form Runner, Type: RFE
