### ISSUE TITLE
JavaScript error when removing image control

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2685] opened 2016-04-05 17:32 UTC
Exact steps TBD. Issues seem to happen with `fb-static-upload-empty` which is not found. It must be removed from the DOM at some point.

![screen shot 2016-04-05 at 10 04 02 am](https://cloud.githubusercontent.com/assets/105769/14291687/80fd16e2-fb19-11e5-8669-d61d0c662a58.png)

**Comment by avernet** [comment] 2016-04-06 18:13
I tried to use the static upload control in Form Builder, but couldn't reproduce this. Re-assigning this to you @ebruchez to see if you can find steps to reproduce.

**Comment by ebruchez** [comment] 2016-04-06 22:08
Steps:

- new form
- make default section repeated
- insert Static Image (will be in 2nd column of default grid)
- delete Static Image
- JavaScript error

**Comment by avernet** [comment] 2016-04-07 18:18
The error happens when the server responds telling the client the `fb-delete-trigger` is visited, in response to the client having told the server the `fb-delete-trigger` lost the focus. This happens when deleting controls in a repeated section; it doesn't need to be an image attachment. But it doesn't happen when deleting a control in a non-repeated section. With a non-repeated section, the `fb-delete-trigger` is found, still inside the `fb-hover` in the cell where the control was deleted, this even if the whole section was replaced on delete by a `<xxf:inner-html>`. This is the case because in `action-icons.coffee`, when we position the "action icons" inside the cell, we remember the id of the grid on which we did that positioning, and upon the next Ajax response, we re-position the action icons in the same cell. But in the case of a repeated section, while the old grid id was `fb≡section-1-control≡xf-39≡tmp-11-tmp≡tmp-7-tmp⊙1`, after the `<xxf:inner-html>`, the id becomes `fb≡section-1-control≡xf-192≡tmp-11-tmp⊙1`, and thus the code isn't able to re-position the action icons inside that grid. A solution is to, when we can't find the grid, put them back under the `.fb-cell-editor`, as we do when the mouse exits a cell. BTW, this issue was already happening with 4.10, so this is a nice catch.

**Closed** 2016-04-07 18:18 UTC
Labels: Form Builder
