### ISSUE TITLE
In Control Settings, cannot edit Alert Message after unchecking checkbox

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5880] opened 2023-06-30 01:06 UTC
Reproduced with 2021.1.9. The problem doesn't happen with 2022.1.4.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/6303513957)

**Comment by ebruchez** [comment] 2023-08-30 03:20
Closing as duplicate of #5945.

**Closed by ebruchez** 2023-08-30 03:20 UTC
