### ISSUE TITLE
Error reported in Form Preview Console when using section template: "Undeclared variable in XPath expression: $form-resources"

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6689] opened 2024-12-28 04:25 UTC
To reproduce, create a new form, add a section template (e.g. Contact information), do Test, and notice the error showing in the Form Preview Console.

![Screenshot 2024-12-27 at 9 24 39 PM](https://github.com/user-attachments/assets/fc87134a-05d1-42eb-a2c3-1d71a282b600)

[+1 from customer](https://3.basecamp.com/3600924/buckets/17077193/messages/8088147557)

**Comment by ebruchez** [comment] 2024-12-28 19:12
Duplicate of #6400.

**Closed by ebruchez** 2024-12-28 19:12 UTC
Labels: Module: Form Builder
