### ISSUE TITLE
Binds order doesn't follow control orders

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#443] opened 2012-09-24 18:49 UTC
1. Create a new form.
2. Add a new column to the left of the existing control.
3. Add an input field in the newly created cell.

View source, and notice how the order of the elements in the instance is the same as the order of the control, but the order of the binds isn't.

**Comment by ebruchez** [comment] 2018-01-13 00:52
Closing as duplicate of #1361.

**Closed by ebruchez** 2018-01-13 00:52 UTC
Labels: 4 Points, Form Builder
