### ISSUE TITLE
Enable authorization service to return information about current user

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1872] opened 2014-08-26 00:13 UTC
The Form Runner persistence API needs to know about the current user (username, roles, and group) to return meaningful results. For this information to be available to the API when it is called by a 3rd-party application, currently Orbeon Forms needs to be deployed twice:
1. Once setup with FORM-based authentication (to be accessed by end-users with a browser).
2. Once with BASIC authentication (to be accessed by 3rd-party applications).

We would like to avoid the need to deploy Orbeon Forms twice. One way to do this would be to:
1. Use a single `war`, disabling authentication for the services (this is already what is [being done](https://github.com/orbeon/orbeon-forms/blob/tag-release-4.6.2-ce/descriptors/orbeon-war-web.xsl#L456) by default).
2. In the PFC, when calling the authorization service, pass the [list of roles](https://github.com/orbeon/orbeon-forms/blob/tag-release-4.6.2-ce/src/resources-packaged/config/properties-form-runner.xml#L86) in a header.
3. In our [simple authorizer](https://github.com/orbeon/orbeon-forms/blob/tag-release-4.6.2-ce/src/main/scala/org/orbeon/oxf/controller/AuthorizerServlet.scala), use that list of roles, and set the `Orbeon-Username`, `Orbeon-Group`, and `Orbeon-Roles` in the response.
4. In the PFC, when an authorization service returns those headers, use their value and take that to the be the authenticated user.

**Comment by ebruchez** [comment] 2021-08-02 23:29
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/chats/1124110061)

**Comment by ebruchez** [comment] 2021-08-02 23:52
Closing as duplicate of #2321 which now has more information.

**Closed** 2021-08-02 23:52 UTC
Labels: Module: Form Runner, Type: RFE
