### ISSUE TITLE
Autosize textarea doesn't grow well in FB/FR

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2313] opened 2015-07-14 17:22 UTC
- new form with Text Area
- set "With Resizing" appearance
- enter a character → ok
- enter a new line → area grows just by a few pixels
- there is always a lot of padding at the bottom

![autosize](https://cloud.githubusercontent.com/assets/105769/8679873/3e45412c-2a12-11e5-9ce7-fd594df3a583.png)

**Comment by avernet** [comment] 2015-07-17 17:57
This issue can be reproduced with the autosize v1 demo, but not with the autosize v2 demo. The reason for using v1 was that it still supported IE8, while v2 will leave the textarea unchanged on IE8. We could:

1. Switch to v2, which should fix this issue, at the cost of losing the autosize feature in IE8.
2. Serve both the v1 and v2 JavaScript, use the v1 code on IE8, and v2 everywhere else.
3. Try to fix the issue in the autosize v1 code.
4. Decide this is a "small cosmetic issue", and close it as "won't fix".

**Comment by avernet** [comment] 2015-08-10 04:59
Resolution:

- We'll implement option 1 above (switch to v2), and if we find that the textarea not resizing on IE8 is a problem for some customers, we'll implement option 2 (using v1 on IE8, v2 on other browsers).
- Tentatively scheduling this for 4.11.

**Closed** 2015-09-02 18:46 UTC
Labels: Cosmetic, Usability, XBL Components
