### ISSUE TITLE
Custom upload widget

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1747] opened 2014-06-03 00:34 UTC
Goals:
- Have a consistent appearance across browsers.
- Be able to control the label on button.

For reference, different methods based on Bootstrap are described [here](http://stackoverflow.com/questions/11235206/twitter-bootstrap-form-file-element-upload-button).

**Comment by ebruchez** [comment] 2018-01-12 19:41
Marking as duplicate of #1238.

**Closed by ebruchez** 2018-01-12 19:41 UTC
Labels: Cosmetic, Form Runner, RFE
