### ISSUE TITLE
REST API to create new instance of a form

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3080] opened 2017-01-23 23:43 UTC
Currently, to programmatically create a new instance of a form, one needs to:

1. Retrieve the form definition using the CRUD API.
2. Extract the content of the `fr-form-data` instance.
3. Generate a new document id, following the same, or a similar, technique used by Form Runner, implemented by [`SecureUtils`](https://github.com/orbeon/orbeon-forms/blob/master/src/main/scala/org/orbeon/oxf/util/SecureUtils.scala)`.randomHexId`
4. Call the CRUD API to store the newly created document.

This RFE calls for a new API to simplify this process. The API would take as:

- Input: app/form name (on the URL).
- Output: new document id (e.g. HTTP header), and empty instance (response body).

The API wouldn't save the document in the database, but it would be up to the caller to call the CRUD API to save it, as in general callers to this API will want to set the value of some fields before the first instance is created.

[+1 from community](http://stackoverflow.com/questions/41761989/integrating-orbeon-with-custom-java-web-aplication)

**Comment by avernet** [comment] 2017-03-16 23:08
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/159f05cf6604d927)

**Comment by ebruchez** [comment] 2017-09-11 18:45
Closing this now as a duplicate of #3318 which covers more.

**Closed by ebruchez** 2017-09-11 18:45 UTC
Labels: Form Runner, RFE
