### ISSUE TITLE
Ability to show errors in `view` mode

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3779] opened 2018-10-16 22:35 UTC
Use case: help-desk person should be able to view data entered by someone else to help them solve possible problems with their data.

Currently, as workaround, form authors can make all the sections read-only for users with a certain role and for those users show errors on form load by running a process that marks everything as visited, but being able to use the `view` mode for this would have the following benefits:

- Provide more assurance that users can't save or autosave data.
- Doesn't require form authors to mark every section read-only upon some condition, and run a process on form load for certain users.
- Provide a better UI.

**Comment by ebruchez** [comment] 2019-03-14 23:24
See #3969 for a similar request which we are implementing now for view/pdf modes.

#3969 doesn't call for showing the errors in the Error Summary, just under the fields. I don't know if that makes it a duplicate of the current issue.

**Comment by ykowalewski** [comment] 2020-11-27 15:21
As I see in #3969 it is enough to see alerts inline. This one issue can be closed.

**Comment by ebruchez** [comment] 2021-08-07 00:28
Closing then.

**Closed by ebruchez** 2021-08-07 00:28 UTC
Labels: Module: Form Runner, Type: RFE
