### ISSUE TITLE
Email to include link to the form

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1452] opened 2013-11-21 20:03 UTC
The [email](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner:-Buttons-and-Processes#email) containing a link back to the form would enable use cases where another user (or the same user) can come back to the form to change/add data.

**Comment by ebruchez** [comment] 2020-06-18 21:58
Duplicate of #4461. Closing.

**Closed by ebruchez** 2020-06-18 21:58 UTC
Labels: Module: Form Runner, Type: RFE
