### ISSUE TITLE
Prevent double submissions

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2068] opened 2015-01-22 00:10 UTC
Once users have filled out and submitted a form, right now they can hit back in their browser, and submit the form again. Orbeon Forms should, by default, prevent this.

**Comment by avernet** [comment] 2015-01-22 00:10
[+1 from discuss](http://discuss.orbeon.com/How-to-implement-a-custom-quot-Finish-page-quot-best-td4659431.html)

**Comment by ebruchez** [comment] 2015-05-15 00:21
Duplicate of #1967, closing.

**Closed by ebruchez** 2015-05-15 00:21 UTC
Labels: Form Runner, RFE
