### ISSUE TITLE
Ability to specify an external label

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4190] opened 2019-09-24 22:22 UTC
Sometimes a label (or possibly hint) needs to be positioned separately from the control. See for example the screenshot below, where an "Explanatory Text" control was used.

One way would be to still, from a UI point of view, use an "Explanatory Text", but to have an option to use it as label for the control. Form Builder would then store the text as the control's label, and then use an `<xf:label for="...">`. This would also be useful for accessibility.

<img width="920" alt="Screen Shot 2019-09-24 at 3 19 31 PM" src="https://user-images.githubusercontent.com/105769/65554534-b9092100-dede-11e9-9e80-3eed26adc227.png">

See also #2865 for a related feature.

**Comment by avernet** [comment] 2021-07-06 21:02
Closing as duplicate of #‌4778 (the issue I am closing is older, but the new issue has more details in its description).

**Closed by avernet** 2021-07-06 21:02 UTC
Labels: Area: Accessibility, Type: RFE
