### ISSUE TITLE
FB: DOMException with Chrome when quickly inserting controls

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3187] opened 2017-05-10 23:45 UTC
Quickly insert controls from toolbox. At some point getting:

```
DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame.
    at Object.get (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/ops/yui/dom/dom.js:98:23)
    at Object.get (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/ops/yui/dom/dom.js:127:45)
    at Object.inDocument (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/ops/yui/dom/dom.js:795:39)
    at Function.xblClass.instance (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/ops/javascript/xforms.js:3280:68)
    at xf_103a73d80e9ced5c1d30bfe14f9381c6c72d08bd (http://localhost:8080/orbeon/fr/orbeon/builder/new:57:21)
    at Ef (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/forms/orbeon/builder/resources/scalajs/orbeon-form-builder.js:92:93)
    at Af.callUserScript (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/forms/orbeon/builder/resources/scalajs/orbeon-form-builder.js:92:277)
    at http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/ops/javascript/orbeon/xforms/server/AjaxServer.js:2107:80
    at NodeList.forEach (<anonymous>)
    at Function._.each._.forEach (http://localhost:8080/orbeon/0f55c3fc5685f7ed8e45e4e18f1ab8912ecb227c/ops/javascript/underscore/underscore.js:79:11)
```

Not getting this with Firefox.

**Comment by avernet** [comment] 2017-05-13 00:08
Closing, as we can't reproduce this with the latest stable release of Chrome: 58.0.3029.110 (64-bit). Erik had reproduced this with a beta.

**Closed by avernet** 2017-05-13 00:08 UTC
Labels: Crasher, Form Builder
