### ISSUE TITLE
`fr:databound-select1` doesn't initialize in new iteration

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4945] opened 2021-07-21 21:54 UTC
To reproduce:

- create new form with repeated grid
- place Dynamic dropdown (defaults to loading list of countries)
- Test, insert row, notice list is empty in new row

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/3973057997#__recording_3976193181)

I reproduce this on master (soon 2021.1) and customer sees this on custom branch.

**Comment by ebruchez** [comment] 2021-07-21 22:05
Interestingly, if I add a row, delete it and then add a row again, it works.

**Comment by ebruchez** [comment] 2021-07-22 01:13
Tricky. Tracing a simple example, I notice this upon new iteration:

- initial creation of the repeat tree
    - `$itemset`: initially evaluates to the empty `itemset` instance root element
    - outer-scoped `$itemset`: initially points to that same element, of course
- refresh
    - `$itemset`: re-evaluates to the root element which now contains the result of the submission
    - outer-scoped `$itemset`: dependencies say NOT to update
    - therefore the evaluation context of the itemset is incorrect and the itemset remains empty

**Comment by ebruchez** [comment] 2021-07-22 03:14
This is a bug in the dependency system. When checking if the value of the variable requires re-evaluation, we run an "interesting" algorithm, which uses a cache.

During the refresh process, we check the controls in order, and so we check the outer `$itemset` variable for iteration 1, and later for iteration 2.

- 1st (existing) iteration returns `false` (don't need an update), because the `xbl-model` for iteration 2 had a structural change and the control belongs to iteration 1. So far so good.
- 2nd (new) iteration returns `false` because it just reuses the result!

So that doesn't work as it stands.

The cache key is made of the following:

- the control's prefixed id
- the prefix of repeat indexes with length equal to the maximum repeat depth of the dependent models for the given control's *binding analysis* (weird)

Concretely, in our case:

- `section-1-section≡grid-1-grid≡control-1-control≡xf-689`
- that control's `control.bindingAnalysis`'s dependent models is `fr-form-model`, which means repeat depth 0
    - so the repeat indexes are not taken into consideration!

What this should do is take `control.valueAnalysis`. In this case, the dependent model would be `section-1-section≡grid-1-grid≡control-1-control≡xbl-model`, so the depth would be 1, and that would be part of the cache key.

**Comment by avernet** [comment] 2021-07-22 12:12
This sounds like a duplicate of #4868:

- [ ] @ebruchez Check if this is indeed the case.
- [ ] @ebruchez If so, when fixed, inform customer who reported the issue that led us to open #4868.

**Closed** 2021-08-04 21:12 UTC
Labels: Area: XBL Components
