### ISSUE TITLE
Implement background upload without iframe/YUI

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3381] opened 2017-12-04 23:45 UTC
We have seen customers send an [`X-Frame-Options` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) to the browser, which can break file upload as it currently alsays uses an `iframe`, through [`YAHOO.util.Connect`](http://yui.github.io/yui2/docs/yui_2.9.0_full/connection/).

Instead, we should use the capability in [XMLHttpRequest 2](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) for file uploads, when available, and only revert to using an `iframe` when necessary. If we drop IE9 support (#3380), we might even be able to always use XMLHttpRequest 2 for file upload, as it seems that [it might already be supported in IE10](https://caniuse.com/#feat=xhr2).

[+1 from customer](https://3.basecamp.com/3600924/buckets/1932446/messages/792116411)

**Comment by ebruchez** [comment] 2018-01-12 19:35
Copied from #3149, which I am marking as a duplicate:

We should be able to use the `File` API.  #1003 also suggests displaying the progress using the `File` API.

See also #1599.

**Comment by ebruchez** [comment] 2020-03-07 00:33
Closing as duplicate of #4290, which was implemented for 2019.2.

**Closed by ebruchez** 2020-03-07 00:33 UTC
Labels: Module: XForms, Type: RFE
