### ISSUE TITLE
Improve image annotation support for larger images

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1077] opened 2013-06-18 00:01 UTC
If the image attached is larger than the available area on screen, the image is cropped on the sides to fit the available space. Ideally, it would be better to have either:
- scrollbars
- scaling
  - done with CSS, i.e. scaling the canvas
  - done resizing the image to the available space, maybe on the client using the canvas

**Comment by ebruchez** [comment] 2016-12-21 22:29
Closing as duplicate of #1312.

**Closed by ebruchez** 2016-12-21 22:29 UTC
Labels: RFE, XBL Components
