### ISSUE TITLE
Summary page: ability to configure processes and links for buttons

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5214] opened 2022-02-09 18:51 UTC
[+1 from user](https://stackoverflow.com/questions/70430719/custom-home-button-in-orbeon-form-builder-summary-page) for configuring the link for the Home button

**Comment by avernet** [comment] 2023-07-04 01:03
Closing as duplicate of #3347.

**Closed by avernet** 2023-07-04 01:03 UTC
Labels: Module: Form Runner, Type: RFE
