### ISSUE TITLE
Ability for the format of number and date to depend on current language

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1494] opened 2014-01-17 18:10 UTC
It might be good enough to make properties like `oxf.xforms.format.input.date` and `oxf.xforms.xbl.fr.number.*` depend on the language, i.e. first using `oxf.xforms.format.input.date.en` or `oxf.xforms.format.input.date.fr` depending on the current language, and if not defined falling back the default provided by `oxf.xforms.format.input.date`.

**Comment by ebruchez** [comment] 2016-11-04 17:30
Closing as duplicate of #1152.

**Closed by ebruchez** 2016-11-04 17:30 UTC
Labels: Form Runner, RFE, XBL Components
