### ISSUE TITLE
Processes: use `if(expr)` instead of `if('expr')`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2941] opened 2016-09-28 06:12 UTC
Requiring quotes around the expression in an `if` is somewhat unexpected, and makes it harder to deal with expressions containing quotes (e.g. `concat()` with a literal string, or call to `instance()`).

[+1 from community](http://stackoverflow.com/a/39356212/5295)

**Comment by ebruchez** [comment] 2016-09-28 13:07
Closing as duplicate of #1256.

**Closed by ebruchez** 2016-09-28 13:07 UTC
Labels: Form Runner, RFE
